### ISSUE TITLE
TS.ADD Ignores new labels

### ISSUE THREAD

**Issue by markusr** [RedisLabsModules/RedisTimeSeries#68]
I don't understand how adding new labels after ```TS.CREATE``` should work.

```
127.0.0.1:6379> keys *
(empty list or set)
127.0.0.1:6379> TS.CREATE testkey LABELS area east
OK
127.0.0.1:6379> TS.INFO testkey
 1) lastTimestamp
 2) (integer) 0
 3) retentionSecs
 4) (integer) 0
 5) chunkCount
 6) (integer) 1
 7) maxSamplesPerChunk
 8) (integer) 360
 9) labels
10) 1) 1) "area"
       2) "east"
11) rules
12) (empty list or set)
```
As expected. Now I add a new time sample with an additional label.

```
127.0.0.1:6379> TS.ADD testkey * 99 LABELS area east type humidity
OK
127.0.0.1:6379> TS.INFO testkey
 1) lastTimestamp
 2) (integer) 1552914091
 3) retentionSecs
 4) (integer) 0
 5) chunkCount
 6) (integer) 1
 7) maxSamplesPerChunk
 8) (integer) 360
 9) labels
10) 1) 1) "area"
       2) "east"
11) rules
12) (empty list or set)
```
The  label ```type``` is completely ignored.

```
127.0.0.1:6379> TS.RANGE testkey - +
1) 1) (integer) 1552914091
   2) "99"
127.0.0.1:6379> TS.MRANGE - + FILTER type=humidity
(empty list or set)
```

Is this the designed and desired behavior?

**Comment by gkorland** [comment]
The labels on are only used on the first call, in the key was not created in the advance.
It's "sugar" API to allow you avoid calling TS.CREATE and then TS.ADD

**Comment by markusr** [comment]
@gkorland  ok. I understand the design. 

I wonder if the call with a non existing label should return an error?
Or only allow optional parameters on empty keys.

**Comment by gkorland** [comment]
@markusr it's a good question but since we feel like performance and high TP/low latency is the most important property for TimeSeries DB, I don't think we should add any runtime checks

**Comment by markusr** [comment]
I agree that for performance it is better to ignore the optional parameters. 
Maybe add this behavior to the documentation?

**Comment by K-Jo** [comment]
@markusr  it's mentioned in the notes: https://oss.redislabs.com/redistimeseries/commands/#update
Please advice if this was not clear enough

**Comment by markusr** [comment]
@K-Jo  Yes, the notes are not clear (at least not to me):

```
When specified, RedisTimeSeries will check if it needs to update the labels and or retentionSecs which introduces additional complexity.
```

My understanding is that RedisTimeSeries will never update the labels (or retentionSecs).

**Comment by K-Jo** [comment]
Ok I will add that executing this check (without updating it) adds time complexity

**Comment by K-Jo** [comment]
https://github.com/RedisLabsModules/RedisTimeSeries/pull/69
