### ISSUE TITLE
Allow adding out of sequence new values to the series

### ISSUE THREAD

**Issue by cur3n4** [RedisLabsModules/RedisTimeSeries#96]
If new values are added to a series out of order, the module returns an error: TSDB: timestamp is too old. 
Would it be possible to allow values for a timestamp < latest series timestamp.
Thanks

**Comment by danni-m** [comment]
@cur3n4 there's a performance tradeoff for adding "not-in-order" samples.
If you would need to insert data in already compacted data structure, it means that every time you do that you move data and reallocate memory (with compression that also means to decompress and compress it again).

It not something we are planning to add at this stage, we are focusing on performance, so we pick this specific tradeoff.
Maybe in the future we will solve this in an optimized way.

**Comment by cur3n4** [comment]
@danni-m Thanks for that, I suspected that was the reason. 
For us, it makes some scenarios somehow tricky to deal with.

In any case, congrats for the library and looking forward to see it evolve.

**Comment by nightwolfz** [comment]
Any plans on adding this? We would be willing to accept any performance trade-off as our use-case is very low on inserts but high on reads

**Comment by ashtul** [comment]
@nightwolfz 
We plan on adding this in the near future. Not sure yet about delete option.

**Comment by pvtpogopuschel** [comment]
@ashtul  Is there an open ticket to track the progress on this issue? I can see there is a branch "out-of-order" that seems to be related to that feature. Also, there are some Pull Requests on this topic (if I am not mistaken), such as https://github.com/RedisTimeSeries/RedisTimeSeries/pull/410

However, this ticket is closed and I have not found an alternative or even a ticket in the 1.4 project.

**Comment by ashtul** [comment]
@pvtpogopuschel 
Please see #413 

Are you testing it? If you encounter any issues, please share them.

**Comment by filipecosta90** [comment]
> you can never guarantee all data always comes in time order
> occasionally slow vs lost data

hi there @fanlix you're totally right. This feauture was added on https://github.com/RedisTimeSeries/RedisTimeSeries/pull/437
and it's present both on v1.4 and master branches
